//
//  TCXBuild.swift
//  CoreTCX
//
//  Created by Vincent Neo on 20/4/2022.
//

import Foundation

public struct TCXBuild {
    var version: TCXVersion
    var type: TCXBuildType?
    
    /**
     
    Garmin Schema Documentation
     A string containing the date and time when an application was built.
     Note that this is not an xsd:dateTime type because this string is
     generated by the compiler and cannot be readily converted to the
     xsd:dateTime format.
     */
    var time: String?
    
    /**
     
    Garmin Schema Documentation
     The login name of the engineer who created this build.
     */
    var builder: String?
}
